### ISSUE TITLE
Display peak and aggregate epidemic sizes on model pages

### ISSUE THREAD

**Issue by jk3141** [epidemics/covid#192] opened 2020-03-19 13:54 UTC
At country pages, derive size of the peak for each trajectory - likely makes sense to take all trajectories, find peaks, and display as range 

(At the peak of the epidemic, under this scenario, there will be 10M-30M active infections, requiring 1.1M to 3M hospital beds and 500k-1M ICU units.
 Overall there will be 200-800M infections, which can lead do 2-15M deaths.)

**Comment by hnykda** [comment] 2020-03-21 12:58
Do you mean the map or the model pages (or the same)? (as the title is different from the description)

**Comment by Bachibouzouk** [comment] 2020-03-21 19:16
As the number stored in the json file are number of people infected per 1000 people, we would need to use population numbers. 

The aggregate is simply the integral of the curves right?

**Comment by jk3141** [comment] 2020-03-22 20:10
yeah, it's the integral, but actually will be directly in some file as the cumulative bumber. and yes will need either multiplying by population or displying as percentage

**Comment by lagerros** [comment] 2020-03-24 02:27
This is a duplicate of #227

**Comment by hnykda** [comment] 2020-03-24 20:19
#277 got closed, so do we want to close this one too?

**Comment by lagerros** [comment] 2020-03-24 20:36
No, this should stay open! It's quite a high priority.

The thing that got closed was making it into **graphs** of stacked bars. Just displaying the total numbers is still [a highly requested feature](https://www.notion.so/Looking-at-e-g-the-US-model-it-s-hard-to-tell-if-weak-mitigation-reduces-total-cases-vs-just-shi-cc1a6b174fd84dfab7232cec28ef2d54).

**Comment by gavento** [comment] 2020-03-24 23:57
@jk3141 

> Overall there will be 200-800M infections, which can lead do 2-15M deaths.)

How do we compute deaths? Plain percentage (or percentage range) seems too simplistic, but would work.

How about a model with 
* One percentage of all
* Additional percentage of people needing but not getting ICU
  * This further depends on how long they failed to get it / how long theu use it? Any simpler but still correct model with less assumptions?
*

**Comment by lagerros** [comment] 2020-03-25 00:28
That model seems good to me, as long as we add some error bars.

**Comment by hnykda** [comment] 2020-03-28 09:32
Hey. I finally moved into this, here are my thoughts:

## "Algorithm"

## Finding peaks if multiple peaks
The problem of second wave is making the above problematic in situations with multiple peaks. Consider `Weak` UK trajectories:
![image](https://user-images.githubusercontent.com/2741256/77819868-7ec34b00-70de-11ea-8067-3ae4eac3fe78.png)

the dots shows the maximums of the each trajectory. The trace13 has peak the next year. From what I have seen  it's somewhat rare, so I can do something like "majority vote": find indexes of maximums, take "median" and then take maximums around e.g. 5 day interval of the median.

**Comment by gavento** [comment] 2020-03-28 09:45
@hnykda I think the intent was to simply write the numbers in text below the graph. And there, we could take the range of the maximums from our traces. (Or something bit more complex, e.g. fit them with some distribution and display e.g. 90% CIs, or just discard top and bottom 1, showing this as 50% CIs ..)

**Comment by hnykda** [comment] 2020-03-28 09:52
But what numbers would you write there? :grin:

**Comment by gavento** [comment] 2020-03-28 09:58
> Overall there will be 200-800M infections, which can lead do 2-15M deaths.)

I will add this to the JSON data (in ~30 minutes? working on something related ..).
Note: It may make sense to display this in % as well.
I will leave out the deaths (not sure about the formula)

> At country pages, derive size of the peak for each trajectory - likely makes sense to take all trajectories, find peaks, and display as range

I think this is just the range of curve maxima. I can add this to the JSON too, if you wish.

> (At the peak of the epidemic, under this scenario, there will be 10M-30M active infections, requiring 1.1M to 3M hospital beds and 500k-1M ICU units.

I am not sure how to compute this ..

**Comment by gavento** [comment] 2020-03-28 10:00
I am not sure how would error bars for values of individual trajectories computed. What do you mean?

**Comment by gavento** [comment] 2020-03-28 10:05
Also, I guess this all is *per mitigation strength*? @jk3141

**Comment by hnykda** [comment] 2020-03-28 10:25
(resolved with gavento from call)

**Comment by hnykda** [comment] 2020-03-29 09:10
#287 resolved part of it, there is a followup in #288

**Closed by hnykda** 2020-03-29 09:10 UTC
Labels: clarification-needed, enhancement, frontend
